version: '3.4'

networks:
  backend:
    driver: bridge

services:
  testtask.api:
    build:
      context: ./Backend
      dockerfile: TestTask/Dockerfile
    container_name: testtask-api
    image: testtask-api:latest
    networks:
      - backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Task4311;Username=postgres;Password=postgres123;
    depends_on:
      - db
    ports:
      - "8003:80"
      - "8083:443"
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: testtask-db
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Task4311
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./Frontend
  #     dockerfile: Dockerfile
  #   container_name: testtask-frontend
  #   image: testtask-frontend:latest
  #   networks:
  #     - frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./Frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - CHOKIDAR_USEPOLLING=true
  #   depends_on:
  #     - testtask.api
  #   restart: unless-stopped

volumes:
  postgres_data: