version: '3.9'

networks:
  backend:
    driver: bridge

services:
  authdb:
    container_name: auth-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - "8007:1433"

  testtask.api:
    container_name: testtask-api
    build:
      context: .
      dockerfile: TestTask/Dockerfile
    networks:
      - backend
    environment:
      - Logstash__Uri=http://logstash:5044
      - Jwt__Secret=superSecretKey@345432242344324245
      - Jwt__Issuer=https://localhost:5001 
      - Jwt__Audience=https://localhost:5001
      - Jwt__TokenValidityInMinutes=1
      - ConnectionStrings__DefaultConnection=Server=authdb;Database=AuthDb2;User Id=sa;Password=password@12345#;TrustServerCertificate=True;
    depends_on:
      - authdb
    ports:
      - "8002:80"
      - "8082:443"
